path: "/Users/michael_khalfin/bosse/Model"
train: "/Users/michael_khalfin/bosse/Model/Train"
test: "/Users/michael_khalfin/bosse/Model/Test"
valid: "/Users/michael_khalfin/bosse/Model/Validate" 

# Classes 
nc: 1 # replace based on your dataset's number of classes 

# Class names 
# replace all class names with your own classes' names 
names: ['marker']